// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHgy0lbKAvpEhDZWH2PYALEBgz2pWv464',
    appId: '1:905610312747:web:fb4fa8ee3c143bb1073e6e',
    messagingSenderId: '905610312747',
    projectId: 'mobile-app-65d1c',
    authDomain: 'mobile-app-65d1c.firebaseapp.com',
    storageBucket: 'mobile-app-65d1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9JAlxrW19-9ggt1vcuNjMLZugfK9YBo4',
    appId: '1:905610312747:android:61e838460af021bf073e6e',
    messagingSenderId: '905610312747',
    projectId: 'mobile-app-65d1c',
    storageBucket: 'mobile-app-65d1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcmaRMOOf3AsszQ1pLVjTSmgsCasHY-ek',
    appId: '1:905610312747:ios:38a8751aa7d10033073e6e',
    messagingSenderId: '905610312747',
    projectId: 'mobile-app-65d1c',
    storageBucket: 'mobile-app-65d1c.firebasestorage.app',
    iosBundleId: 'com.example.ircell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcmaRMOOf3AsszQ1pLVjTSmgsCasHY-ek',
    appId: '1:905610312747:ios:38a8751aa7d10033073e6e',
    messagingSenderId: '905610312747',
    projectId: 'mobile-app-65d1c',
    storageBucket: 'mobile-app-65d1c.firebasestorage.app',
    iosBundleId: 'com.example.ircell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHgy0lbKAvpEhDZWH2PYALEBgz2pWv464',
    appId: '1:905610312747:web:20a1f81a9ea86eb8073e6e',
    messagingSenderId: '905610312747',
    projectId: 'mobile-app-65d1c',
    authDomain: 'mobile-app-65d1c.firebaseapp.com',
    storageBucket: 'mobile-app-65d1c.firebasestorage.app',
  );

}